### ISSUE TITLE
IndexError: list index out of range get_active_host

### ISSUE THREAD

**Issue by enira** [enira/qnd-backup#102]
When creating starting fresh if the application hasn't initialized the hosts yet: press backup.
```
IndexError: list index out of range
[2017-08-06 21:41:35,218] ERROR in app: Exception on /api/xen/vms/full/1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/marshalling.py", line 101, in wrapper
    resp = f(*args, **kwargs)
  File "/opt/qndbackup/qnd/api/xen/endpoints/vms.py", line 32, in get
    env = Flow.instance().get_environment(pool_id)
  File "/opt/qndbackup/qnd/xen/flow.py", line 64, in get_environment
    obj["vms"] = self._poolcache[pool_id]["backup"].get_vms()
  File "/opt/qndbackup/qnd/xen/xenbackup.py", line 121, in get_vms
    return self.get_active_host().get_vms()
  File "/opt/qndbackup/qnd/xen/xenbackup.py", line 94, in get_active_host
    return self.servers[0]
IndexError: list index out of range
```

**Comment by enira** [comment]
It does not crash application or block flow.
